package:
  name: "tempo"
  version: "0.0.1.dev"
about:
  summary: "Tempo: a Bayesian algorithm for circadian phase inference in scRNA-seq data."
source:
  path: ../src/tempo
build:
  script: python setup.py install
channels:
  - anaconda
  - pytorch
  - bioconda
  - defaults
  - conda-forge
requirements:
  run:
    - python=3.8.5
    - alabaster=0.7.12
    - anndata=0.7.5
    - appdirs=1.4.4
    - appnope=0.1.2
    - argon2-cffi=20.1.0
    - astroid=2.5
    - async_generator=1.10
    - attrs=20.3.0
    - babel=2.9.0
    - backcall=0.2.0
    - biopython=1.78
    - biothings_client=0.2.6
    - blas=1.0
    - bleach=3.2.1
    - blosc=1.20.1
    - brotlipy=0.7.0
    - bzip2=1.0.8
    - ca-certificates=2021.7.5
    - cairo=1.14.12
    - certifi=2021.5.30
    - cffi=1.14.4
    - chardet=4.0.0
    - click=7.1.2
    - cloudpickle=1.6.0
    - colorama=0.4.4
    - cryptography=3.3.1
    - cycler=0.10.0
    - cytoolz=0.11.0
    - dask-core=2020.12.0
    - datacache=1.1.5
    - decorator=4.4.2
    - defusedxml=0.6.0
    - docutils=0.16
    - entrypoints=0.3
    - ffmpeg=4.3
    - fontconfig=2.13.0
    - freetype=2.10.4
    - get_version=2.1
    - gettext=0.19.8.1
    - glib=2.66.1
    - gmp=6.1.2
    - gnutls=3.6.5
    - gtfparse=1.2.1
    - h5py=2.10.0
    - hdf5=1.10.4
    - icu=58.2
    - idna=2.10
    - igraph=0.7.1
    - imageio=2.9.0
    - imagesize=1.2.0
    - importlib-metadata=2.0.0
    - importlib_metadata=2.0.0
    - intel-openmp=2019.4
    - ipykernel=5.3.4
    - ipython=7.22.0
    - ipython_genutils=0.2.0
    - isort=5.8.0
    - jedi=0.18.0
    - jinja2=2.11.2
    - joblib=1.0.0
    - jpeg=9b
    - json5=0.9.5
    - jsonschema=3.2.0
    - jupyter_client=6.1.7
    - jupyter_core=4.7.0
    - jupyterlab=2.2.9
    - jupyterlab_pygments=0.1.2
    - jupyterlab_server=1.2.0
    - kiwisolver=1.3.0
    - lame=3.100
    - lazy-object-proxy=1.6.0
    - lcms2=2.11
    - legacy-api-wrap=1.2
    - leidenalg=0.7.0
    - libcxx=10.0.0
    - libedit=3.1.20191231
    - libffi=3.3
    - libgfortran=3.0.1
    - libiconv=1.16
    - libllvm10=10.0.1
    - libpng=1.6.37
    - libsodium=1.0.18
    - libtiff=4.1.0
    - libuv=1.40.0
    - libxml2=2.9.10
    - llvm-openmp=10.0.0
    - llvmlite=0.34.0
    - loompy=3.0.6
    - lz4-c=1.9.2
    - lzo=2.10
    - markupsafe=1.1.1
    - matplotlib=3.3.2
    - matplotlib-base=3.3.2
    - mccabe=0.6.1
    - memoized-property=1.0.3
    - memory_profiler=0.58.0
    - mistune=0.8.4
    - mkl=2019.4
    - mkl-service=2.3.0
    - mkl_fft=1.2.0
    - mkl_random=1.1.1
    - mock=4.0.3
    - mpmath=1.1.0
    - mygene=3.2.2
    - natsort=7.1.0
    - nbclient=0.5.1
    - nbconvert=6.0.7
    - nbformat=5.0.8
    - ncurses=6.2
    - nest-asyncio=1.4.3
    - nettle=3.4.1
    - networkx=2.5
    - ninja=1.10.2
    - notebook=6.1.6
    - numba=0.51.2
    - numexpr=2.7.2
    - numpy=1.19.2
    - numpy-base=1.19.2
    - numpy_groupies=0.9.13
    - olefile=0.46
    - openh264=2.1.0
    - openssl=1.1.1l
    - packaging=20.8
    - pandas=1.2.0
    - pandoc=2.11
    - pandocfilters=1.4.3
    - parso=0.7.0
    - patsy=0.5.1
    - pcre=8.44
    - pexpect=4.8.0
    - pickleshare=0.7.5
    - pillow=8.1.0
    - pip=20.3.3
    - pixman=0.40.0
    - progressbar33=2.4
    - prometheus_client=0.9.0
    - prompt-toolkit=3.0.8
    - psutil=5.7.2
    - ptyprocess=0.7.0
    - pycairo=1.19.1
    - pycparser=2.20
    - pyensembl=1.9.1
    - pygments=2.7.3
    - pylint=2.7.4
    - pynndescent=0.5.1
    - pyopenssl=20.0.1
    - pyparsing=2.4.7
    - pyrsistent=0.17.3
    - pysocks=1.7.1
    - pytables=3.6.1
    - python=3.8.5
    - python-annoy=1.16.3
    - python-dateutil=2.8.1
    - python-igraph=0.7.1.post7
    - python_abi=3.8
    - pytz=2020.5
    - pywavelets=1.1.1
    - pyyaml=5.3.1
    - pyzmq=20.0.0
    - readline=8.0
    - requests=2.25.1
    - scanpy=1.6.0
    - scikit-image=0.16.2
    - scikit-learn=0.23.2
    - scipy=1.5.2
    - scrublet=0.2.1
    - scvelo=0.2.2
    - seaborn=0.11.1
    - send2trash=1.5.0
    - serializable=0.2.0
    - setuptools=51.1.2
    - setuptools-scm=5.0.1
    - setuptools_scm=5.0.1
    - simplejson=3.17.2
    - sinfo=0.3.1
    - six=1.15.0
    - snowballstemmer=2.0.0
    - sphinx=3.4.3
    - sphinxcontrib-applehelp=1.0.2
    - sphinxcontrib-devhelp=1.0.2
    - sphinxcontrib-htmlhelp=1.0.3
    - sphinxcontrib-jsmath=1.0.1
    - sphinxcontrib-qthelp=1.0.3
    - sphinxcontrib-serializinghtml=1.1.4
    - sqlite=3.33.0
    - statsmodels=0.12.1
    - stdlib-list=0.7.0
    - sympy=1.6.2
    - tbb=2020.3
    - terminado=0.9.2
    - testpath=0.4.4
    - threadpoolctl=2.1.0
    - tinytimer=0.0.0
    - tk=8.6.10
    - toml=0.10.2
    - toolz=0.11.1
    - torchaudio=0.7.0
    - torchvision=0.8.1
    - tornado=6.1
    - tqdm=4.55.1
    - traitlets=5.0.5
    - typechecks=0.1.0
    - typing_extensions=3.7.4.3
    - umap-learn=0.5.0
    - urllib3=1.26.2
    - wcwidth=0.2.5
    - webencodings=0.5.1
    - wheel=0.36.2
    - wrapt=1.12.1
    - xlrd=1.2.0
    - xz=5.2.5
    - yaml=0.2.5
    - zeromq=4.3.3
    - zipp=3.4.0
    - zlib=1.2.11
    - zstd=1.4.5
    - pip:
      - ax-platform==0.2.2
      - blitz-bayesian-pytorch==0.2.7
      - botorch==0.5.1
      - gpytorch==1.5.1
      - plotly==5.3.1
      - pytorch-nlp==0.5.0
      - scikit-misc==0.1.3
      - tenacity==8.0.1
      - torch==1.9.1
      - typeguard==2.12.1
